#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../../.." && pwd)
CONFIG_PATH=${CONFIG_PATH:-"${SCRIPT_DIR}/phase6_pi_runtime_ddp.json"}

# Default phase6 spike-controller knobs. Override from the shell for sweeps.
export NCCL_PHASE6_W_STEP=${NCCL_PHASE6_W_STEP:-0.4}
export NCCL_PHASE6_KP=${NCCL_PHASE6_KP:-1.0}
export NCCL_PHASE6_KI=${NCCL_PHASE6_KI:-0.05}
export NCCL_PHASE6_EPOCH_MS=${NCCL_PHASE6_EPOCH_MS:-5}
export NCCL_PHASE6_MIN_SAMPLES=${NCCL_PHASE6_MIN_SAMPLES:-4}
export NCCL_PHASE6_WARMUP_EPOCHS=${NCCL_PHASE6_WARMUP_EPOCHS:-1}
export NCCL_PHASE6_COOLDOWN_EPOCHS=${NCCL_PHASE6_COOLDOWN_EPOCHS:-2}
export NCCL_PHASE6_STABLE_EPOCHS=${NCCL_PHASE6_STABLE_EPOCHS:-5}
export NCCL_PHASE6_THRESHOLD_HIGH_PCT=${NCCL_PHASE6_THRESHOLD_HIGH_PCT:-100}
export NCCL_PHASE6_THRESHOLD_LOW_PCT=${NCCL_PHASE6_THRESHOLD_LOW_PCT:-15}
export NCCL_PHASE6_THROUGHPUT_LOW_PCT=${NCCL_PHASE6_THROUGHPUT_LOW_PCT:-85}
export NCCL_PHASE6_WSTALL_HIGH_PCT=${NCCL_PHASE6_WSTALL_HIGH_PCT:-20}
export NCCL_PHASE6_INTEGRAL_LIMIT_PCT=${NCCL_PHASE6_INTEGRAL_LIMIT_PCT:-500}
export NCCL_PHASE6_ALPHA_FAST_PCT=${NCCL_PHASE6_ALPHA_FAST_PCT:-30}
export NCCL_PHASE6_ALPHA_SLOW_PCT=${NCCL_PHASE6_ALPHA_SLOW_PCT:-5}

exec bash "${REPO_ROOT}/research/code/phase4/run_b4_matrix.sh" --config "${CONFIG_PATH}" "$@"
